### ISSUE TITLE
Allow enabling/disabling of parameter logging on calls to execute/executemany.

### ISSUE THREAD

**Issue by escheie** [Teradata/PyTd#14]
From Teradata Developer Exchange post by psobczak:

> It would be nice if we could get more granular control over logging levels. I like INFO level as a default  but when running batch INSERTS with thousands of rows this actually logs every row passed to the  INSERT statement resulting in a very large log file. I created my own logger and tried to change logging level to WARNING just for the INSERT using Python standard logger.setlevel function but that doesn't seem to work. Setlevel executes successfully but it does not seem to affect what is actually logged by Teradata module.
It would be great if there was an option to override session logging level through a parameter to Execute/Executemany.

**Comment by fxstein** [comment]
Maybe consider frequency based logging for DML. Show first and last INSERTs but only show frequency in between. e.g. every 10k or 100k records.

**Comment by escheie** [comment]
Two new parameters have been added to execute and executemany.

logParamCharLimit - This parameter limits the size of an individual parameter in the log.   The default is 80 characters.   When truncated, an ellipsis ("...") is added.   This functionality already existed in previous releases but was not configurable.   When this value is zero, no truncation is performed.

logParamFrequency -  This parameter controls how many individual parameter sets are logged.   The default is 1 which is the current previous behavior.   Setting this value to X means that every Xth parameter set will be logged, in addition to the first and last parameter set.   When this value is set to zero, parameter logging is disabled.
