### ISSUE TITLE
"Rolling back open transaction" warning message

### ISSUE THREAD

**Issue by padhia** [Teradata/PyTd#24]
When executing following code. A warning message is displayed that I don't believe should be generated.

```python
#! /usr/bin/env python

from __future__ import (absolute_import, division, print_function, unicode_literals)
from teradata.tdodbc import *

import logging

logging.basicConfig(format="%(levelname)s: %(message)s")

cnx = connect(system='mytd', username='xxxx', password='xxxx', transactionMode='Teradata')
csr = cnx.cursor()

csr.execute('select * from dbc.dbcinfov')

print([list(r) for r in csr.fetchall()])

csr.close()
cnx.close()
```

Output:
```
[[u'LANGUAGE SUPPORT MODE', u'Standard'], [u'RELEASE', u'15.00.01.01'], [u'VERSION', u'15.00.01.01']]
WARNING: Rolling back open transaction for session 1007 so it can be closed.
```

Environment is: WIndows 7, Python 2.7.10, teradata package version 15.10.0.11

**Comment by escheie** [comment]
You should either enable autoCommit or invoke commit after calling execute.   Leaving transactions uncommitted when closing a connection is not good practice and hence the warning.

Autocommit is disabled by default when directly accessing the tdodbc module as per the PEP-0249 standard:

> Note that if the database supports an auto-commit feature, this must be initially off

The PEP-0249 standard also states:

> closing a connection without committing the changes first will cause an implicit rollback to be performed.
