### ISSUE TITLE
Specifying default database on connect

### ISSUE THREAD

**Issue by padhia** [Teradata/PyTd#25]
Since both ODBC and REST API support default database to be specified during connect time, will it be possible to add support for a new parameter in `connect` call to allow for specifying default database value? 

It seems `connect` in `teradata.tdodbc` supports passing arbitrary keyword arguments which can be used for supplying default database, but I wasn't able to find a similar work-around in `teradata.tdrest` module.

**Comment by escheie** [comment]
Yes, great point, will target for next patch.

Thanks,
-Eric

**Comment by escheie** [comment]
The same keyword "database" that can be used for ODBC can now be used for REST too.
