### ISSUE TITLE
Specifying logmech on connect

### ISSUE THREAD

**Issue by padhia** [Teradata/PyTd#26]
This is similar to #25. Please add support for specifying logon mechanism during `connect` with either `teradata.tdodbc` or `teradata.tdrest`. 

Also, this is not directly related to `PyTd`, but I could never get LDAP connection working using Teradata REST services. I am pretty sure I created correct system definition, even specifying LDAP as default authentication. Connection testing with Authentication selected as LDAP always fails with following message.

> Incorrect UserID, Password or Account

**Comment by escheie** [comment]
I can confirm that LDAP is not working with REST and have engaged with the REST team to get the issue resolved.   To set the logmech for ODBC, you can set authentication="LDAP".  Once the functionality is working for REST,  I will add the same "authentication" keyword support to the tdrest module.

**Comment by escheie** [comment]
LDAP support will be implemented in the upcoming TDREST patch release (tracked by REST-323).

**Comment by padhia** [comment]
Thanks for the update!
