### ISSUE TITLE
Extremely slow when fetching large volume of data compared with pyodbc/jdbc

### ISSUE THREAD

**Issue by yinhao** [Teradata/PyTd#29]
Hi,

I compare the operating time when fetching large amount of dataset among teradata python module, ODBC(with pyodbc), and JDBC(with jaydebeapi).

It seems that it takes too long when fetching large amount of dataset, I used pandas read_sql to get the result, but the performance is same when using session.fetchall() directly.

Here is the result comparision for sample size = 10000, 50000, 100000, 500000.  The ODBC driver performs awesome, however it cannot fetch DECIMAL data properly.

-------time of sample size - 10000 --------
ODBC: 0:00:01.216346
PyTD: 0:00:09.844205
JDBC: 0:00:03.215781

-------time of sample size - 50000 --------
ODBC: 0:00:01.270462
PyTD: 0:00:35.796656
JDBC: 0:00:08.558847

-------time of sample size - 100000 --------
ODBC: 0:00:02.567906
PyTD: 0:01:09.826736
JDBC: 0:00:18.884113

-------time of sample size - 500000 --------
ODBC: 0:00:08.691584
PyTD: 0:05:34.788833
JDBC: 0:01:27.788149

**Comment by escheie** [comment]
Looks like the culprit here is the overhead involved with calling the ODBC driver from Python using ctypes.  Currently the Python module calls the ODBC function SQLGetData to fetch each column of each row individually, so if the result set is large, the function call overhead adds up quickly, resulting in poor performance.   Looks like this could be improved considerably by binding the result columns to memory structures first using SQLBindCol, then calling SQLFetchScroll to populate the in memory structures with the data from multiple rows, thus reducing considerably the number of calls from Python into the ODBC driver.  I will try to get a fix implemented soon, it may take a week or two though as its not a trivial change.

**Comment by escheie** [comment]
@yinhao - Can you provide the number of columns and data types used in your benchmark.

Thanks,
-Eric

**Comment by yinhao** [comment]
Hi Eric,

Thank you for the prompt reply. I just select 3 columns with VARCHAR(20).

teradata module has the better interface to Teradata than pyodbc/jaydebeapi, it would be even greater if the time to fetch large dataset could be reduced

**Comment by escheie** [comment]
I've been able to reduce the fetch times considerably (~10x improvement) by making the changes described above.   Working now on adding back in LOB support and adding more test cases.

**Comment by escheie** [comment]
A fix has been committed to drastically improve performance.  There are also several settings that may help to improve fetch performance.

1.   Set cursor.arraysize to a value greater than 1.   This attribute as documented in the Python Database specification controls how many rows are fetched at one time.  Increasing this value can increase throughput at the cost of higher memory consumption.   Note that this value is not used when LOB data is being returned with a ResultSet.  
2.  Use charset=UTF8 on Unix/Linux and charset=UTF16 on Windows/Mac.   These encodings are what is expected by Python, so if these charsets are also the session charset, the ODBC driver doesn't have to spend time performing character conversions.

Thanks,
-Eric

**Comment by pGit1** [comment]
@escheie ,

You said: "Set cursor.arraysize to a value greater than 1."

How do I do this (code)? How to modify "charset"?

**Comment by pGit1** [comment]
I did a pip install Teradata. Should I install from the main branch?

**Comment by rbinnun** [comment]
Was this fixed in python 2.7 as well?
I'm using python 2.7 and a fetchall using jaydebeapi is taking forever...
Setting `arraysize` to greater than 1 doesn't seem to improve things.
