### ISSUE TITLE
Cursor lastrowid attribute

### ISSUE THREAD

**Issue by sandan** [Teradata/PyTd#30]
Has there been any attempt at implementing the lastrowid attribute of the Cursor object for tdodbc? 
(mentioned here in the PEP spec: https://www.python.org/dev/peps/pep-0249/#lastrowid). From what I read in the ODBC Driver for Teradata User Guide, Teradata ODBC seems to have support for Autogenerated-Key retrieval.

**Comment by escheie** [comment]
According to the Teradata ODBC documentation, autogenerated-key retrieval is handled via a ResultSet.  In your DSN, you specify the ReturnGeneratedKeys=C option.  Then generated keys are returned as the actual result rows of the cursor itself and not as a cursor attribute .  See #7 for more details.   Note there is a bug in the ODBC driver where this does not work for parameterized queries.
