### ISSUE TITLE
Error message from query not displayed in python

### ISSUE THREAD

**Issue by jnlaia** [Teradata/PyTd#34]
When a query has failed, it would be very useful to have the reason shown in the python error message. I'm using 15.10.0.13 version, python 2.7.11.

Imagine I don't have a table called b. If I run the query

`select a from b`

I should get an error "Object 'b' does not exist." However, when running that query through PyTd, that error message is not displayed. I get instead

`InterfaceError: ('SQL_ERROR', 'SQL_ERROR returned from SQLGetDiagRecW.')`

which makes it harder to debug.

**Comment by escheie** [comment]
This is a duplicate of #33 which is fixed in version 15.10.00.14.
