### ISSUE TITLE
Add support for Teradata 16.0 ODBC driver

### ISSUE THREAD

**Issue by escheie** [Teradata/PyTd#50]
The driver named changed from "Teradata" to "Teradata Database ODBC Driver 16.00" in the Teradata ODBC 16.0 driver.   

This results in the following error when attempting to use the 16.0 ODBC driver.

`Data source name not found and no default driver specified`

**Comment by escheie** [comment]
The following features have been implemented:

1. Added code to query the driver manager for all the available drivers and include them in the log file.
2. Allow uses to select the driver they want to use by setting a 'driver' parameter.
3. Search the available drivers for one containing 'Teradata' so that setting driver name is not required.
4. Log a warning when more than one 'Teradata' driver is available but the user does not specify which one to use.

Example Log Messages:

2016-08-22 13:30:08,592 - teradata.tdodbc - INFO - Available drivers: SQL Server, Teradata, Teradata Database ODBC Driver 16.00
2016-08-22 13:30:08,592 - teradata.tdodbc - WARNING - More than one driver found for 'Teradata'.  Using 'Teradata Database ODBC Driver 16.00'.  Specify the 'driver' option to select a specific driver.

**Comment by jackalwoods** [comment]
well i used  - 
session = udaExec.connect(method="odbc", system="192.168.252.128",  username="dbc", password="dbc", DRIVER="Teradata Database ODBC Driver 16.00");

but getting below error - 
DatabaseError: [HY000] [Teradata][ODBC Teradata Driver] Loading the Teradata ICU Library Failed. Error is: 126, The driver returned invalid (or failed to return) SQL_DRIVER_ODBC_VER: 03.80

Any idea what is wrong?

**Comment by joooosh** [comment]
I am getting the same error as @jackalwoods 

Were you able to find a resolution?

**Comment by dineshkumarPS** [comment]
Hi I am also getting the same error please share the info if u solve
