### ISSUE TITLE
How to Login TD Session with Encrypted PAssword??

### ISSUE THREAD

**Issue by pGit1** [Teradata/PyTd#63]
If I need to share a script with someone that logs in via `session = udaExec.connect(... Authentication="LDAP")` how do I do this without revealing my password?

**Comment by escheie** [comment]
The script does not need to have the password hard coded in it.  The password can be provided in an external configuration file or via Teradata Wallet if using ODBC as the connect method.

**Comment by pGit1** [comment]
Any example code on how to do this? I am definitely using a hard coded
method right now.

**Comment by escheie** [comment]
First add your password to tdwallet (e.g. we will call our password "password_example").

`tdwallet add password_example`

Then reference the password stored in tdwallet in the script.

`session = udaExec.connect(method="odbc", ..., password="$$tdwallet(password_example)");`

**Comment by pGit1** [comment]
@escheie  thanks for your help but I don't think I am filling in the blanks here. 

1. What is "tdwallet"? I have no module that I can import that is called tdwallet. 
2. Even in the example you give above 

>  session = udaExec.connect(method="odbc", ..., password="$$tdwallet(password_example)"); 

"password_example" is still in the connection string. Sorry I have to reopen this. It is critical. 

Can you please provide a more detailed example of how to do this?

**Comment by escheie** [comment]
tdwallet is a command line tool that acts as a password vault for Teradata Tools and Utilities .   If you Google for Teradata Wallet, it should provide additional details if you need to install it.   The password will not be contained in the script but will be looked up from the local wallet where the script is executed.

**Comment by pGit1** [comment]
Ok thanks!
