### ISSUE TITLE
Port not working when part of config

### ISSUE THREAD

**Issue by johnrc** [Teradata/PyTd#69]
I have a config file where the port is declared. Like so:

```
# Default Data Source Configuration
[DEFAULT]
method=rest
host=my.example.com
port=1443
protocol=https
charset=UTF8
```

Whenever this is used it throws an exception because the config keys and values are converted in unicode. Unfortunately, `httplib.HTTPSConnection()` only accepts a number or string for the port value.

```
InterfaceError: ('REST_ERROR', 'Error accessing my.example.com:1443. ERROR:  getaddrinfo() argument 2 must be integer or string')
```

PR #68 fixes this issue.

**Comment by escheie** [comment]
Fixed by 269b916.
