### ISSUE TITLE
.Execute Fails with 3707 error trying to create/replace macro

### ISSUE THREAD

**Issue by DaveRoth** [Teradata/PyTd#88]
It looks like the execute code doesn't accurately identify the end of macro DDL and throws this error:

3707, "[42000] [Teradata][ODBC Teradata Driver][Teradata Database] Syntax error, expected something like ')' between ';' and the end of the request. "

**Comment by escheie** [comment]
Here is an excerpt from the documentation:

> A semi-colon is used as the default delimiter when specifying multiple SQL statements.   Any occurrence of a semi-colon outside of a SQL string literal or comments is treated as a delimiter.   When SQL scripts contain SQL stored procedures that contain semi-colons internal to the procedure, the delimiter should be change to something other than the default.  To use a different character sequence as the delimiter, the delimiter parameter can be used.  E.g.
> 
> `session.execute(file="myqueries.sql", delimiter=";;")`

Does this help resolve your problem?

**Comment by DaveRoth** [comment]
Yes, I did try changing to a delimiter of ');' thinking that might get it to see the end of macro, but got same error.


thanks


Dave

________________________________

**Comment by escheie** [comment]
Can you provide sample script to reproduce your error?

**Comment by DaveRoth** [comment]
Hey just went on vacation will submit in a week but it’s the basic format. Doesn’t matter if comment there or not

Replace macro xxx
(
Unparalleled
)
As
(
Select xxx
;

);

Comment on xxx ‘stuff’;


Dave Roth



On Dec 7, 2017, at 12:08, Eric Scheie <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you provide sample script to reproduce your error?

**Comment by DaveRoth** [comment]
ok, back :)

here is the full macro text that fails:

[MODEL_STANDARDS_CLOB_USAGE.txt](https://github.com/Teradata/PyTd/files/1572439/MODEL_STANDARDS_CLOB_USAGE.txt)

and this is the error again

![capture](https://user-images.githubusercontent.com/8184910/34168258-0a6e0926-e4b2-11e7-88d2-bdb9c13bb9ec.PNG)

**Comment by escheie** [comment]
I was able to execute the script using the following statement:

session.execute(file="MODEL_STANDARDS_CLOB_USAGE.txt", delimiter=";;"):

I just had to add an extra ";" at the end of the macro.  E.g. ");;"

**Comment by DaveRoth** [comment]
well darn, that does get me by the prior error but still throws an only DDL allowed error because it tried to run the replace macro and the comment in the same query. Did you remove the comment by chance?

**Comment by escheie** [comment]
No, I just added the extra semi-colon after the macro so PyTd knew where to split the two queries.

**Comment by DaveRoth** [comment]
So, I got a version to work by splitting out the macro and comment into a string array then executing both parts. A little clunky but workable. Maybe we need a special macro process ?

**Comment by DaveRoth** [comment]
Got it. Yeah that would work but I would never get them to accept non standard coding :) Thanks for all your help!

**Comment by DaveRoth** [comment]
Closing this as I was able to code a work around in my modules.
