### ISSUE TITLE
How to set ODBC driver 16.20 for Ubuntu?

### ISSUE THREAD

**Issue by dclong** [Teradata/PyTd#91]
Teradata has release ODBC driver 16.20 and has deb package for Ubuntu. Has anyone successfully configure ODBC on Ubuntu. If so, would you share the instructions?

**Comment by escheie** [comment]
Just gave this a try and it worked fine.  

The instructions are the same as getting it to work on rpm based linux distributions.  E.g.

1) Install the ODBC driver: `dpkg -i tdodbc1620-16.20.00.00-1.noarch.deb`

I did receive an error performing this step: 

> Error: lib32stdc++6 package is not installed.
>  tdodbc1620 requires lib32stdc++6 package
>  Please install the required package and try again.

I resolved by running:  `apt install lib32stdc++6`

2) Set environment variable:  `export ODBCINI=/opt/teradata/client/ODBC_64/odbc.ini`
3) Install the Teradata Python Module:  `pip install teradata`

After performing the 3 steps above, I was able to successfully run a python script that queried Teradata.
