### ISSUE TITLE
udaExec.connect is breaking with  @ in password

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [Teradata/PyTd#96]
My password contains @ and udaExec.connect is not creating connection. When I change the password it's working.

c = udaExec.connect(method="odbc", system='<SYSTEM>',
                          username='<USERNAME>', password='test@1234')

**Comment by escheie** [comment]
I am not able to reproduce your problem.   I created a password with an "@" and had no problem logging in.    What is the error you are getting?

**Comment by praveenkanamarlapudi** [comment]
It's working fine. Sorry we probably messed up somewhere else.  Thanks for checking it.
