### ISSUE TITLE
not able to connect to teradata with python 3.5

### ISSUE THREAD

**Issue by vedbeau** [Teradata/PyTd#99]
Hi,
Please help me to fix this issue

>>> import teradata
>>> udaExec = teradata.UdaExec (appName="HelloWorld", version="1.0",logConsole=False)                                 >>> conn = udaExec.connect(method="odbc", DBCName="tdsitcop1.us.dell.com", UID="ravina", PWD="xxx", authentication="LDAP")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/datascience/anaconda3/lib/python3.5/site-packages/teradata/udaexec.py", line 183, in connect
    **args))
  File "/opt/datascience/anaconda3/lib/python3.5/site-packages/teradata/tdodbc.py", line 454, in __init__
    checkStatus(rc, hDbc=self.hDbc, method="SQLDriverConnectW")
  File "/opt/datascience/anaconda3/lib/python3.5/site-packages/teradata/tdodbc.py", line 231, in checkStatus
    raise DatabaseError(i[2], u"[{}] {}".format(i[0], msg), i[0])
teradata.api.DatabaseError: (0, '[I] [. Check that the ODBC driver is installed and the ODBCINI or ODBCINST environment variables are correctly set.')
>>>
>>>

**Comment by vedbeau** [comment]
Created a file udaexec.ini in /root,but still getting the same problem.
Please help
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20180312025436-20
 *             Host: dstmdldev01
 *         Platform: Linux-3.10.0-693.5.2.el7.x86_64-x86_64-with-redhat-7.4-Maipo
 *          OS User: root
 *   Python Version: 3.5.2
 *  Python Compiler: GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
 *     Python Build: ('default', 'Jul  2 2016 17:53:06')
 *  UdaExec Version: 15.10.0.21
 *     Program Name:
 *      Working Dir: /root
 *          Log Dir: /root/logs
 *         Log File: /root/logs/HelloWorld.20180312025436-20.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/root/udaexec.ini: Found', '/root/udaexec.ini: Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20180312025436-20;ClientUser=root;Production=False;udaAppLogFile=/root/logs/HelloWorld.20180312025436-20.log;UtilityName=PyTd;UtilityVersion=15.10.0.21

**Comment by ebyhr** [comment]
I can connect to teradata server with Python 3.5. Here is my example. 
Have you installed [Teradata ODBC Driver for Linux](https://downloads.teradata.com/download/connectivity/odbc-driver/linux)?

```sh
~/GitHub/tdpy $ pyenv version
3.5.0 (set by /Users/ebyhr/GitHub/tdpy/.python-version)
~/GitHub/tdpy $ 
~/GitHub/tdpy $ cat tdpy.py
import teradata
 
udaExec = teradata.UdaExec (appName="tdpy", version="1.0",logConsole=False) 
session = udaExec.connect(method="odbc", system="wbtlabserver.teradata.com", username="testuser", password="***");
 
for row in session.execute("SELECT GetQueryBand()"):
    print(row)

session2 = udaExec.connect("WBT");
for row in session2.execute("SELECT GetQueryBand()"):
    print(row)
~/GitHub/tdpy $ 
~/GitHub/tdpy $ cat udaexec.ini
# Application Configuration
[CONFIG]
appName=TdPy
version=0.1
logConsole=False
dataSourceName=WBT
table=DBC.DBCInfo 
 
# Default Data Source Configuration
[DEFAULT]
method=odbc
charset=UTF8
 
# Data Source Definition
[WBT]
system=wbtlabserver.teradata.com
username=testuser
password=***
~/GitHub/tdpy $ 
~/GitHub/tdpy $ python tdpy.py 
Row 1: [=S> ApplicationName=tdpy;Version=1.0;JobID=20180314220449-8;ClientUser=ebyhr;Production=False;udaAppLogFile=/Users/ebyhr/GitHub/tdpy/logs/tdpy.20180314220449-8.log;UtilityName=PyTd;UtilityVersion=15.10.0.21;]
Row 1: [=S> ApplicationName=tdpy;Version=1.0;JobID=20180314220449-8;ClientUser=ebyhr;Production=False;udaAppLogFile=/Users/ebyhr/GitHub/tdpy/logs/tdpy.20180314220449-8.log;UtilityName=PyTd;UtilityVersion=15.10.0.21;]
~/GitHub/tdpy $ 
```

**Comment by vedbeau** [comment]
Hi ,
Thanks for the update
Below is the code which i'm using in python.I'm able to connect using BTEQ with LDAP credentials.
I'm getting [Teradata][ODBC Teradata Driver][Teradata Database] (210) The UserId, Password or Account is invalid. FailCode = -8017') while executing in python.
But i am able to connect through BTEQ 

import teradata
udaExec = teradata.UdaExec (appName="HelloWorld", version="1.0",logConsole=True)
session = udaExec.connect(method="odbc", system="xxxx",username="ravina",password="xxxx");

udaexec.ini file
# Application Configuration
[CONFIG]
appName=HelloWorld
version=0.1
logConsole=True
dataSourceName=Teradata ODBC DSN
table=DBC.DBCInfo

# Default Data Source Configuration
[DEFAULT]
method=odbc
charset=UTF8

# Data Source Definition
[Teradata ODBC DSN]
system=hostname
username=ravina
password=xxxx

Thanks in advance

**Comment by ebyhr** [comment]
Would you change following 2 lines?
1. Specify the data source name like this  `session = udaExec.connect("Teradata ODBC DSN");`
2. Add `authentication=LDAP` in udaexec.ini

python script
```py
import teradata

udaExec = teradata.UdaExec (appName="HelloWorld", version="1.0",logConsole=True)
session = udaExec.connect("Teradata ODBC DSN");
```

udaexec.ini
```ini
# Application Configuration
[CONFIG]
appName=HelloWorld
version=0.1
logConsole=True
dataSourceName=Teradata ODBC DSN
table=DBC.DBCInfo

# Default Data Source Configuration
[DEFAULT]
method=odbc
charset=UTF8
authentication=LDAP

# Data Source Definition
[Teradata ODBC DSN]
system=hostname
username=ravina
password=xxxx
```

**Comment by vedbeau** [comment]
Hi,
Now i'm getting the below error after the above changes
Check that the ODBC driver is installed and the ODBCINI or ODBCINST environment variables are correctly set.')
-----------
echo $ODBCINI
/opt/teradata/client/16.20/odbc_64/odbc.ini
------------

odbc.ini
[ODBC]
# For Data Direct to load its error messages
# Data Direct Driver Manager looks for the messages here:
# "/opt/teradata/client/16.20/locale/xx_xx/LC_MESSAGES/"
InstallDir=/opt/teradata/client/16.20/odbc_64
Trace=no
Pooling=yes

[ODBC Data Sources]
Teradata ODBC DSN=Teradata Database ODBC Driver 16.20

[Teradata ODBC DSN]
# This key is not necessary and is only to give a description of the data source.
Description=Teradata Database ODBC Driver 16.20

# Driver: The location where the ODBC driver is installed to.
Driver=/opt/teradata/client/16.20/odbc_64/lib/tdataodbc_sb64.so

# Required: These values can also be specified in the connection string.
DBCName=hostname
UID=ravina

**Comment by vedbeau** [comment]
>>> session = udaExec.connect("Teradata ODBC DSN")
2018-03-15 06:03:19,666 - teradata.udaexec - INFO - Creating connection: {'externalDSN': 'Teradata ODBC DSN', 'username': 'ravina', 'authentication': 'LDAP', 'method': 'odbc', 'system': '10.233.131.80', 'charset': 'UTF8', 'password': 'XXXXXX'}
2018-03-15 06:03:19,667 - teradata.tdodbc - INFO - Loading ODBC Library: libodbc.so
2018-03-15 06:03:19,670 - teradata.tdodbc - INFO - Available drivers: ODBC Drivers, Teradata
2018-03-15 06:03:19,672 - teradata.udaexec - ERROR - Unable to create connection: {'externalDSN': 'Teradata ODBC DSN', 'username': 'ravina', 'authentication': 'LDAP', 'method': 'odbc', 'system': '10.233.131.80', 'charset': 'UTF8', 'password': 'XXXXXX'}

**Comment by vedbeau** [comment]
Hi ,
I'm able to connect now.
I appreciate your support.
Thank you so much
